import { expect, test } from '@playwright/test'
import { routeApi } from './fixtures/routeApi'

test('creates, edits, resizes and reopens a note using the UI', async ({ page }) => {
  const api = await routeApi(page)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/project/route-project')
  await page.getByRole('button', { name: 'Add note', exact: true }).click()
  await page.getByRole('textbox', { name: /^Name/ }).fill('Review details')
  await page.getByLabel('Note text', { exact: true }).fill('First line\n<script>example</script>')
  await page.getByLabel('Note color', { exact: true }).selectOption('blue')
  await page.getByRole('button', { name: 'Save Configuration', exact: true }).click()
  const note = page.locator('.vue-flow__node-note')
  await expect(note).toHaveCount(1)
  await expect(note).toContainText('Review details')
  await expect(note).toContainText('<script>example</script>')
  await expect(note.locator('script')).toHaveCount(0)
  await expect(note.locator('.canvas-note')).toHaveAttribute('data-color', 'blue')
  const before = await note.boundingBox()
  await note.click()
  await page.getByRole('button', { name: 'Close configuration panel', exact: true }).click()
  const handle = note.locator('.vue-flow__resize-control.bottom.right.handle')
  const box = await handle.boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await page.mouse.down()
  await page.mouse.move(box!.x + 110, box!.y + 70, { steps: 10 })
  await page.mouse.up()
  await expect.poll(async () => (await note.boundingBox())!.width).toBeGreaterThan(before!.width + 50)
  const savedWidth = await note.evaluate(element => element.style.width)
  await page.getByRole('button', { name: 'Save project', exact: true }).click()
  await page.reload()
  await expect(note).toContainText('Review details')
  await expect(note).toContainText('First line')
  await expect(note.locator('.canvas-note')).toHaveAttribute('data-color', 'blue')
  await expect.poll(() => note.evaluate(element => element.style.width)).toBe(savedWidth)
  await note.click()
  await page.getByRole('button', { name: 'Delete node', exact: true }).click()
  await page.getByRole('dialog', { name: 'Delete node', exact: true }).getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(note).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(note).toContainText('Review details')
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(note).toHaveCount(0)
  expect(api.state.writes).toEqual([])
})
