import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { routeApi } from './fixtures/routeApi'

test('desktop sidebar supports nested routes, collapse and ordinary browser keys', async ({ page }, testInfo) => {
  const api = await routeApi(page)
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/project/route-project')
  await expect(page.getByTestId('canvas-wrapper')).toBeVisible()
  const navigation = page.getByRole('navigation', { name: 'Primary', exact: true })
  await page.screenshot({ path: testInfo.outputPath('project-desktop.png') })
  await expect(navigation.getByRole('link', { name: 'Projects', exact: true })).toHaveAttribute('aria-current', 'location')
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click()
  await navigation.getByRole('link', { name: 'Catalog', exact: true }).click()
  await expect(page).toHaveURL(/\/catalog$/)
  await expect(page.getByRole('button', { name: 'Expand sidebar', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Expand sidebar', exact: true })).toBeVisible()
  const prevented = await page.evaluate(() => ['v', 'c', 'n', 'r', 'f', 'g'].flatMap(key => [false, true].map(ctrlKey => {
    const event = new KeyboardEvent('keydown', { key, ctrlKey, cancelable: true, bubbles: true })
    document.body.dispatchEvent(event)
    return event.defaultPrevented
  })))
  expect(prevented).not.toContain(true)
  await expect(page).toHaveURL(/\/catalog$/)
  expect(api.state.writes).toEqual([])
})

test('mobile navigation traps focus, closes with Escape and follows links', async ({ page }, testInfo) => {
  await routeApi(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const opener = page.getByRole('button', { name: 'Open navigation', exact: true })
  await opener.click()
  const dialog = page.getByRole('dialog', { name: 'Navigation', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('link', { name: 'Settings', exact: true }).focus()
  await page.keyboard.press('Tab')
  expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('mobile-navigation.png') })
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(opener).toBeFocused()
  await opener.click()
  await dialog.getByRole('link', { name: 'Sources', exact: true }).click()
  await expect(page).toHaveURL(/\/sources$/)
  await expect(dialog).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('project components can be added without dragging, then undone and redone', async ({ page }) => {
  await routeApi(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/project/route-project?tab=config')
  await page.getByTestId('mobile-drawer-toggle').click()
  const drawer = page.getByRole('dialog', { name: 'Project tools', exact: true })
  await drawer.getByRole('button', { name: 'Add virtual machine', exact: true }).click()
  await expect(drawer).not.toBeVisible()
  await expect(page).toHaveURL(/tab=canvas.*node=/)
  await page.getByRole('button', { name: 'Close configuration panel', exact: true }).click()
  const nodes = page.locator('.vue-flow__node')
  const addedCount = await nodes.count()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(nodes).toHaveCount(addedCount - 1)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(nodes).toHaveCount(addedCount)
  await page.getByRole('button', { name: 'Search project', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
})

for (const theme of ['light', 'dark']) {
  test(`appearance persists and navigation passes accessibility checks in ${theme}`, async ({ page }, testInfo) => {
    await routeApi(page)
    await page.goto('/settings')
    await page.getByLabel('Theme', { exact: true }).selectOption(theme)
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    await page.reload()
    await expect(page.getByLabel('Theme', { exact: true })).toHaveValue(theme)
    await page.goto('/project/route-project')
    await expect(page.getByTestId('canvas-wrapper')).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`project-${theme}.png`) })
    const results = await new AxeBuilder({ page }).include('[data-testid="primary-sidebar"]').include('[data-testid="project-sidebar"]').analyze()
    expect(results.violations).toEqual([])
    await page.keyboard.press('Tab')
    await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused()
    await page.keyboard.press('Enter')
    await expect(page.locator('main')).toBeFocused()
  })
}
